### ISSUE TITLE
ValueError: Protocol message has no singular "snippet_template" field.

### ISSUE THREAD

**Issue by Crystark** [hindol/google-native-bid-requester#1]
Hi,

Thanks for this updated version. I'm seeing the following error when running the requester:

```
Traceback (most recent call last):
  File "requester.py", line 355, in <module>
    main()
  File "requester.py", line 351, in main
    PrintSummary(logger_obj, opts.sample_encrypted_price)
  File "requester.py", line 202, in PrintSummary
    summarizer.Summarize()
  File "/tmp/google-native-bid-requester-master/log.py", line 311, in Summarize
    self.ValidateAd(ad, i, record)
  File "/tmp/google-native-bid-requester-master/log.py", line 560, in ValidateAd
    if ad.HasField(field):
  File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 598, in HasField
    'Protocol message has no singular "%s" field.' % field_name)
ValueError: Protocol message has no singular "snippet_template" field.
```

Here's the command I ran:

```
python requester.py --url=http://localhost/my/path --max_qps=100 --requests=10000
```

Am I doing something wrong ?
Thanks

**Comment by ShemetulskiyDmitriy** [comment]
In log.py used deprecated fields: template_parameter and snippet_template. Remove the logic that uses those fields in log.py and all will be well. Or set this fields as DEPRECATED_ in requester.py and log.py

**Comment by Crystark** [comment]
Thanks, That's what I ended up doing :) sorry for not updating it here earlier.

**Comment by ghost** [comment]
@ShemetulskiyDmitriy Can you kindly submit a pull request? Sorry for not getting back to this earlier. I was on a long vacation and just returned.

**Comment by ShemetulskiyDmitriy** [comment]
hindol-viz, oki. But i'll do it later, for now i havn't time
